#!/usr/bin/env node
/*
 * sync-vocab.js
 * -------------
 * Single source of truth: vocabulary.json (repo root).
 * This script:
 *   1. Injects vocabulary.json into src/App.jsx as SEED_VOCAB
 *      (between the SEED_VOCAB:BEGIN / SEED_VOCAB:END markers)
 *   2. Copies vocabulary.json to www/ and public/ so all three
 *      tracked locations are always identical.
 *
 * Runs automatically before every build via the "prebuild" hook
 * in package.json. Can also be run manually: node sync-vocab.js
 *
 * RULE: edit ONLY vocabulary.json. Never hand-edit the SEED_VOCAB
 * block in App.jsx - it is generated output and will be overwritten.
 */

"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const VOCAB_PATH = path.join(ROOT, "vocabulary.json");
const APP_PATH = path.join(ROOT, "src", "App.jsx");
const COPIES = [
  path.join(ROOT, "www", "vocabulary.json"),
  path.join(ROOT, "public", "vocabulary.json"),
];

const BEGIN = "/* SEED_VOCAB:BEGIN -- GENERATED by sync-vocab.js from vocabulary.json. DO NOT EDIT BY HAND. */";
const END = "/* SEED_VOCAB:END */";

// ---- load + validate source ----
let data;
try {
  data = JSON.parse(fs.readFileSync(VOCAB_PATH, "utf8"));
} catch (e) {
  console.error("sync-vocab: FAILED to parse vocabulary.json:", e.message);
  process.exit(1);
}
const vocab = data.vocabulary;
if (!Array.isArray(vocab) || vocab.length < 750) {
  console.error("sync-vocab: vocabulary.json has", vocab && vocab.length, "words (<750). Refusing to sync a degraded file.");
  process.exit(1);
}
const seen = new Set();
for (const w of vocab) {
  if (!w.id || !w.basque || !w.english || !w.cefr || !w.topic) {
    console.error("sync-vocab: entry missing required field:", JSON.stringify(w).slice(0, 120));
    process.exit(1);
  }
  if (seen.has(w.id)) {
    console.error("sync-vocab: duplicate id:", w.id);
    process.exit(1);
  }
  seen.add(w.id);
}

// ---- 1. inject into App.jsx between markers ----
let src = fs.readFileSync(APP_PATH, "utf8");
const b = src.indexOf(BEGIN);
const e = src.indexOf(END);
if (b === -1 || e === -1 || e < b) {
  console.error("sync-vocab: SEED_VOCAB markers not found in src/App.jsx. Aborting (nothing modified).");
  process.exit(1);
}
const block =
  BEGIN + "\n" +
  "const SEED_VOCAB=[\n" +
  vocab.map((w) => JSON.stringify(w)).join(",\n") +
  "\n];\n" +
  END;
const updated = src.slice(0, b) + block + src.slice(e + END.length);
if (updated !== src) {
  fs.writeFileSync(APP_PATH, updated);
  console.log("sync-vocab: SEED_VOCAB regenerated in src/App.jsx (" + vocab.length + " words)");
} else {
  console.log("sync-vocab: src/App.jsx already up to date (" + vocab.length + " words)");
}

// ---- 2. mirror vocabulary.json to www/ and public/ ----
const canonical = fs.readFileSync(VOCAB_PATH, "utf8");
for (const p of COPIES) {
  const dir = path.dirname(p);
  if (!fs.existsSync(dir)) { console.log("sync-vocab: skip (no dir):", p); continue; }
  const current = fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null;
  if (current !== canonical) {
    fs.writeFileSync(p, canonical);
    console.log("sync-vocab: updated", path.relative(ROOT, p));
  } else {
    console.log("sync-vocab: in sync", path.relative(ROOT, p));
  }
}

console.log("sync-vocab: done.");
