#!/usr/bin/env node
/*
 * sync-vocab.js
 * -------------
 * Single source of truth: vocabulary.json (repo root).
 * This script:
 *   1. Injects vocabulary.json into src/App.jsx as SEED_VOCAB
 *      (between the SEED_VOCAB:BEGIN / SEED_VOCAB:END markers)
 *   2. Copies vocabulary.json to www/ and public/ so all three
 *      tracked locations are always identical.
 *
 * Runs automatically before every build via the "prebuild" hook
 * in package.json. Can also be run manually: node sync-vocab.js
 *
 * RULE: edit ONLY vocabulary.json. Never hand-edit the SEED_VOCAB
 * block in App.jsx - it is generated output and will be overwritten.
 */

"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const VOCAB_PATH = path.join(ROOT, "vocabulary.json");
const APP_PATH = path.join(ROOT, "src", "App.jsx");
const COPIES = [
  path.join(ROOT, "www", "vocabulary.json"),
  path.join(ROOT, "public", "vocabulary.json"),
];

const BEGIN = "/* SEED_VOCAB:BEGIN -- GENERATED by sync-vocab.js from vocabulary.json. DO NOT EDIT BY HAND. */";
const END = "/* SEED_VOCAB:END */";
const S_BEGIN = "/* SEED_STORIES:BEGIN -- GENERATED by sync-vocab.js from vocabulary.json. DO NOT EDIT BY HAND. */";
const S_END = "/* SEED_STORIES:END */";
const LEVELS = ["A1", "A2", "B1", "B2"];

// ---- load + validate source ----
let data;
try {
  data = JSON.parse(fs.readFileSync(VOCAB_PATH, "utf8"));
} catch (e) {
  console.error("sync-vocab: FAILED to parse vocabulary.json:", e.message);
  process.exit(1);
}
const vocab = data.vocabulary;
if (!Array.isArray(vocab) || vocab.length < 750) {
  console.error("sync-vocab: vocabulary.json has", vocab && vocab.length, "words (<750). Refusing to sync a degraded file.");
  process.exit(1);
}
const seen = new Set();
for (const w of vocab) {
  if (!w.id || !w.basque || !w.english || !w.cefr || !w.topic) {
    console.error("sync-vocab: entry missing required field:", JSON.stringify(w).slice(0, 120));
    process.exit(1);
  }
  if (seen.has(w.id)) {
    console.error("sync-vocab: duplicate id:", w.id);
    process.exit(1);
  }
  seen.add(w.id);
}

// stories ship in the same payload as the words so a story can never reference
// vocabulary the app has not got: one fetch, one cache, always consistent.
// They are validated here rather than at runtime, because a malformed story
// should stop a build rather than reach anyone's phone.
const stories = data.stories;
if (!Array.isArray(stories) || !stories.length) {
  console.error("sync-vocab: vocabulary.json has no stories array. Refusing to sync.");
  process.exit(1);
}
const storySeen = new Set();
for (const s of stories) {
  const where = "story " + (s && s.id ? s.id : JSON.stringify(s).slice(0, 60));
  if (!s.id || !s.title || !s.titleEn || !s.level || !s.intro) {
    console.error("sync-vocab: " + where + " is missing a required field.");
    process.exit(1);
  }
  if (LEVELS.indexOf(s.level) === -1) {
    console.error("sync-vocab: " + where + " has level '" + s.level + "', expected one of " + LEVELS.join("/") + ".");
    process.exit(1);
  }
  if (storySeen.has(s.id)) {
    console.error("sync-vocab: duplicate story id:", s.id);
    process.exit(1);
  }
  storySeen.add(s.id);
  if (!Array.isArray(s.lines) || !s.lines.length) {
    console.error("sync-vocab: " + where + " has no lines.");
    process.exit(1);
  }
  for (let i = 0; i < s.lines.length; i++) {
    const ln = s.lines[i];
    if (typeof ln.tr !== "string" || !ln.tr) {
      console.error("sync-vocab: " + where + " line " + (i + 1) + " has no translation.");
      process.exit(1);
    }
    if (!Array.isArray(ln.w) || !ln.w.length) {
      console.error("sync-vocab: " + where + " line " + (i + 1) + " has no words.");
      process.exit(1);
    }
    // each word is a [basque, english] pair; a ragged pair renders a blank gloss
    for (const pair of ln.w) {
      if (!Array.isArray(pair) || pair.length !== 2 || typeof pair[0] !== "string" || typeof pair[1] !== "string") {
        console.error("sync-vocab: " + where + " line " + (i + 1) + " has a malformed word pair: " + JSON.stringify(pair));
        process.exit(1);
      }
    }
  }
}

// Lessons still live in src/App.jsx as hand-written data, and nothing checked
// them: lessonWords() silently skips a wordId it cannot resolve, so a typo or
// an omission just produces a shorter lesson. That is how "Months of the Year"
// shipped teaching ten of the twelve months. Check them here instead.
function validateLessons(vocabIds) {
  const appSrc = fs.readFileSync(APP_PATH, "utf8");
  const start = appSrc.indexOf("var LESSONS=[");
  const chapStart = appSrc.indexOf("var CHAPTERS=[");
  if (start === -1) {
    console.log("sync-vocab: LESSONS array not found, skipping lesson checks");
    return;
  }
  const lblock = appSrc.slice(start, chapStart > start ? chapStart : undefined);
  const marks = [];
  const idRe = /\bid:\s*"(l\d+_[a-z0-9]+)"/g;
  let m;
  while ((m = idRe.exec(lblock)) !== null) marks.push({ at: m.index, id: m[1] });
  if (!marks.length) {
    console.log("sync-vocab: no lessons parsed, skipping lesson checks");
    return;
  }
  const lessonIds = new Set();
  let problems = 0;
  marks.forEach(function (mk, i) {
    const chunk = lblock.slice(mk.at, i + 1 < marks.length ? marks[i + 1].at : lblock.length);
    if (lessonIds.has(mk.id)) {
      console.error("sync-vocab: duplicate lesson id: " + mk.id);
      problems++;
    }
    lessonIds.add(mk.id);
    const wm = /wordIds:\s*\[([^\]]*)\]/.exec(chunk);
    if (!wm) {
      console.error("sync-vocab: lesson " + mk.id + " has no wordIds.");
      problems++;
      return;
    }
    const ids = (wm[1].match(/"([^"]+)"/g) || []).map(function (s) { return s.slice(1, -1); });
    if (!ids.length) {
      console.error("sync-vocab: lesson " + mk.id + " has an empty wordIds list.");
      problems++;
    }
    const unknown = ids.filter(function (w) { return !vocabIds.has(w); });
    if (unknown.length) {
      console.error("sync-vocab: lesson " + mk.id + " references word ids that do not exist: " + unknown.join(", "));
      problems++;
    }
    const dupes = ids.filter(function (w, j) { return ids.indexOf(w) !== j; });
    if (dupes.length) {
      console.error("sync-vocab: lesson " + mk.id + " repeats word ids: " + [...new Set(dupes)].join(", "));
      problems++;
    }
  });
  if (problems) {
    console.error("sync-vocab: " + problems + " lesson problem(s). Refusing to sync.");
    process.exit(1);
  }
  console.log("sync-vocab: " + marks.length + " lessons check out");
}
validateLessons(seen);

// ---- 1. inject into App.jsx between markers ----
let src = fs.readFileSync(APP_PATH, "utf8");
const b = src.indexOf(BEGIN);
const e = src.indexOf(END);
if (b === -1 || e === -1 || e < b) {
  console.error("sync-vocab: SEED_VOCAB markers not found in src/App.jsx. Aborting (nothing modified).");
  process.exit(1);
}
const block =
  BEGIN + "\n" +
  "const SEED_VOCAB=[\n" +
  vocab.map((w) => JSON.stringify(w)).join(",\n") +
  "\n];\n" +
  END;
let updated = src.slice(0, b) + block + src.slice(e + END.length);
if (updated !== src) {
  console.log("sync-vocab: SEED_VOCAB regenerated in src/App.jsx (" + vocab.length + " words)");
} else {
  console.log("sync-vocab: src/App.jsx already up to date (" + vocab.length + " words)");
}

// the bundled stories, so a fresh install with no network still has them
const sb = updated.indexOf(S_BEGIN);
const se = updated.indexOf(S_END);
if (sb === -1 || se === -1 || se < sb) {
  console.error("sync-vocab: SEED_STORIES markers not found in src/App.jsx. Aborting (nothing modified).");
  process.exit(1);
}
const sBlock =
  S_BEGIN + "\n" +
  "var SEED_STORIES=[\n" +
  stories.map((s) => JSON.stringify(s)).join(",\n") +
  "\n];\n" +
  S_END;
const withStories = updated.slice(0, sb) + sBlock + updated.slice(se + S_END.length);
if (withStories !== updated) {
  console.log("sync-vocab: SEED_STORIES regenerated in src/App.jsx (" + stories.length + " stories)");
} else {
  console.log("sync-vocab: stories already up to date (" + stories.length + " stories)");
}
updated = withStories;
if (updated !== src) fs.writeFileSync(APP_PATH, updated);

// ---- 2. mirror vocabulary.json to www/ and public/ ----
const canonical = fs.readFileSync(VOCAB_PATH, "utf8");
for (const p of COPIES) {
  const dir = path.dirname(p);
  if (!fs.existsSync(dir)) { console.log("sync-vocab: skip (no dir):", p); continue; }
  const current = fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null;
  if (current !== canonical) {
    fs.writeFileSync(p, canonical);
    console.log("sync-vocab: updated", path.relative(ROOT, p));
  } else {
    console.log("sync-vocab: in sync", path.relative(ROOT, p));
  }
}

// reads the lesson path out of src/App.jsx. returns null if the file or the
// arrays are not where we expect, so a refactor there degrades to leaving the
// homepage numbers untouched rather than stamping a wrong one.
function countLessons() {
  const appPath = path.join(ROOT, "src", "App.jsx");
  if (!fs.existsSync(appPath)) return null;
  const src = fs.readFileSync(appPath, "utf8");
  const start = src.indexOf("var LESSONS=[");
  const chapStart = src.indexOf("var CHAPTERS=[");
  if (start === -1 || chapStart === -1) return null;
  const block = src.slice(start, chapStart > start ? chapStart : undefined);
  // slice the array into one chunk per lesson, then ask each whether it is Pro
  const marks = [];
  const idRe = /\bid:\s*"l\d+_[a-z0-9]+"/g;
  let m;
  while ((m = idRe.exec(block)) !== null) marks.push(m.index);
  if (!marks.length) return null;
  let free = 0;
  marks.forEach(function (at, i) {
    const chunk = block.slice(at, i + 1 < marks.length ? marks[i + 1] : block.length);
    if (!/\bpro:\s*true/.test(chunk)) free++;
  });
  const chapters = (src.slice(chapStart).split("];")[0].match(/\{\s*n:\s*\d+/g) || []).length;
  if (!chapters) return null;
  return { total: marks.length, free: free, chapters: chapters };
}

// ---- 3. stamp live counts into the site pages ----
// the ikasiandgo.com pages quote the vocabulary size via <span data-count="words">
// and friends, so the site never advertises a stale number. Missing file or
// missing markers is not an error: a page simply gets nothing stamped.
const SITE_PAGES = ["index.html", "about.html"];
const topicCount = new Set(vocab.map(function (w) { return w.topic; })).size;
// per-topic counts in the Inside section carry data-topic="<key>" on the <b>,
// so those numbers cannot drift either as words are added.
const perTopic = vocab.reduce(function (acc, w) {
  acc[w.topic] = (acc[w.topic] || 0) + 1;
  return acc;
}, {});
// the lesson path lives in src/App.jsx, not vocabulary.json, so count it there.
// lessons are appended over time and some are Pro-gated; stamping total, free
// and chapter counts keeps the site from quoting a number that has moved on.
const lessons = countLessons();
SITE_PAGES.forEach(function (name) {
  const p = path.join(ROOT, name);
  if (!fs.existsSync(p)) {
    console.log("sync-vocab: skip (no page): " + name);
    return;
  }
  const page = fs.readFileSync(p, "utf8");
  const stamped = page
    .replace(/(<span data-count="words">)[^<]*(<\/span>)/g, "$1" + vocab.length + "$2")
    .replace(/(<span data-count="topics">)[^<]*(<\/span>)/g, "$1" + topicCount + "$2")
    .replace(/(<span data-count="lessons">)[^<]*(<\/span>)/g, function (m, open, close) {
      return lessons ? open + lessons.total + close : m;
    })
    .replace(/(<span data-count="lessons-free">)[^<]*(<\/span>)/g, function (m, open, close) {
      return lessons ? open + lessons.free + close : m;
    })
    .replace(/(<span data-count="chapters">)[^<]*(<\/span>)/g, function (m, open, close) {
      return lessons ? open + lessons.chapters + close : m;
    })
    .replace(/(<b data-topic="([a-z_-]+)">)[^<]*(<\/b>)/g, function (m, open, key, close) {
      return open + (perTopic[key] || 0) + close;
    });
  if (stamped !== page) {
    fs.writeFileSync(p, stamped);
    console.log("sync-vocab: " + name + " counts updated (" + vocab.length + " words, " + topicCount + " topics)");
  } else {
    console.log("sync-vocab: " + name + " counts already current");
  }
});

console.log("sync-vocab: done.");
